# Generated by Django 5.1.1 on 2025-11-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('image_url', models.URLField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
